src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @ORM\Table(name="events")
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $event_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->event_date;
    }

    public function setEventDate(\DateTimeInterface $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Repository\EventRepository;
use DateTimeZone;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class EventController extends AbstractController
{
    /**
     * @Route("/events", name="events")
     */
    public function index(EventRepository $eventRepository)
    {
        $events = $eventRepository->findAll();

        return $this->render('events/index.html.twig', compact('events'));
    }

    /**
     * @Route("/events/create", name="events_create")
     */
    public function create(Request $request, EntityManagerInterface $em)
    {
        $data = $request->request->all();
        
        if($request->getMethod() == 'POST') {
            $event = new Event();
            $event->setTitle($data['title']);
            $event->setDescription($data['description']);
            
            $event->setEventDate(new \DateTime(
                $data['event_date'], 
                new DateTimeZone('America/Sao_Paulo')
            ));

            $em->persist($event);
            $em->flush();

            return $this->redirectToRoute('events');
        }

        return $this->render('events/create.html.twig');
    }


    /**
     * @Route("/events/edit/{event}", name="events_edit")
     */
    public function edit(Request $request, EntityManagerInterface $em, Event $event)
    {
        $data = $request->request->all();

        if ($request->getMethod() == 'POST') {
            
            $event->setTitle($data['title']);
            $event->setDescription($data['description']);
            
            $event->setEventDate(new \DateTime(
                $data['event_date'], 
                new DateTimeZone('America/Sao_Paulo')
            ));

            $em->flush();

            return $this->redirectToRoute('events');
        }

        return $this->render('events/edit.html.twig', compact('event'));
    }


    /**
     * @Route("/events/remove/{event}", name="events_remove")
     */
    public function remove(EntityManagerInterface $em, Event $event)
    {
        $em->remove($event);
        $em->flush();

        return $this->redirectToRoute('events');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <div class="row mb-5">
            <div class="container">
                <a href="{{path('events')}}">Listar Eventos</a> |
                <a href="{{path('events_create')}}">Criar Eventos</a>
            </div>
        </div>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/events/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <form action="{{path('events_create')}}" method="post">
        <div class="form-group">
            <label>Titulo do Evento</label>
            <input type="text" class="form-control" name="title">
        </div>

        <div class="form-group">
            <label>Descrição Rápida</label>
            <input type="text" class="form-control" name="description">
        </div>

        <div class="form-group">
            <label>Quando Acontece?</label>
            <input type="text" class="form-control" name="event_date">
        </div>

        <button class="btn btn-lg btn-success">Criar Evento</button>
    </form>
{% endblock %}

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <form action="{{path('events_edit', {'event': event.id})}}" method="post">
        <div class="form-group">
            <label>Titulo do Evento</label>
            <input type="text" class="form-control" name="title" value="{{event.title}}">
        </div>

        <div class="form-group">
            <label>Descrição Rápida</label>
            <input type="text" class="form-control" name="description" value="{{event.description}}">
        </div>

        <div class="form-group">
            <label>Quer mudar o dia?</label>
            <input type="text" class="form-control" name="event_date" value="{{event.eventDate|date('Y-m-d H:i:s')}}">
        </div>

        <button class="btn btn-lg btn-success">Atualizar Evento</button>
    </form>
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Evento</th>
                <th>Quando?</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for event in events %}
            <tr>
                <td>{{event.id}}</td>
                <td>{{event.title}}</td>
                <td>{{event.eventDate|date('d/m/Y H:i:s')}}</td>
                <td>
                    <a href="{{path('events_edit', {'event': event.id})}}" class="btn btn-warning btn-sm">Editar</a>
                    <a href="{{path('events_remove', {'event': event.id})}}" class="btn btn-danger btn-sm">Remover</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}